# SQLite version 3.x
#   gem install sqlite3
#
development:
  adapter: postgresql
  database: trailer_app_development
  host: localhost
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: trailer_app_test
  host: localhost
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: trailer_app_prod
  pool: 5
  timeout: 5000